name: Test C++ Build

on:
#  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: powershell
        # working-directory: .\Source

    steps:
#    - uses: actions/checkout@v2
#    - name: Add msbuild to PATH
#      uses: microsoft/setup-msbuild@v1.0.1
#      #with:
#        #vswhere-path: #optional
#        #vs-version: '[16.5.4,16.5.4)'
      
#    - name: MSBuild
#      working-directory: testMDI
#      run: msbuild testMDI.vcxproj

    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"

    - name: get pullrequest comment
      env:
        ENV_PR_BODY: ${{github.event.pull_request.body}}
        ENV_PR_TITLE: ${{github.event.pull_request.title}}
        
      run: |
        $env_pr_body =  $env:ENV_PR_BODY -replace "`r","" -replace "`n",", " -replace "`"","" -replace "'",""
        $env_pr_body
        $env_pr_title =  $env:ENV_PR_TITLE -replace "`r","" -replace "`n",", " -replace "`"","" -replace "'",""
        $env_pr_title
        
        


