name: Label PR as approved
on: 
#  pull_request:
#    types: [submitted]
  pull_request_review:
    types: [submitted]

jobs:
    
  DumpContext:
      name: Dump GitHub context
      runs-on: ubuntu-latest
      steps:
        - name: Github Context
          env:
            GITHUB_CONTEXT: ${{ toJson(github) }}
          run: echo "$GITHUB_CONTEXT"
      
  labelDevelopWhenApproved:
    name: Label develop when approved
    if: github.event.base.ref == 'master'
    runs-on: ubuntu-latest
    steps:
    - name: Label when approved
      uses: abinoda/label-when-approved-action@1.0.5
      env:
        APPROVALS: "1"
        # APPROVALS: "2"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
        REMOVE_LABEL: "review%20required,requires%20changes"

#  labelOtherWhenApproved:
#    name: Label other when approved
#    if: github.event.base.ref != 'master'
#    runs-on: ubuntu-latest
#    steps:
#    - name: Label when approved
#      uses: abinoda/label-when-approved-action@1.0.5
#      env:
#        APPROVALS: "1"
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        ADD_LABEL: "approved"
#        REMOVE_LABEL: "review%20required,requires%20changes"

